version: "3.8"

services:
  postgres:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: devpassword
      POSTGRES_DB: solana_index
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  indexer:
    build: .
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: postgres://postgres:devpassword@postgres:5432/solana_index?sslmode=disable

volumes:
  pgdata:
